name: Deployment

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Install ğŸ”§
      run: npm ci

    - name: Build ğŸ› ï¸
      run: npm run build --if-present

    - name: Deploy ğŸš€
      uses: abinmn/gcp-storage-bucket-action@v1
      with:
        service_key: ${{ secrets.GCP_SERVICE_KEY }}
        build_folder: ${{ github.workspace }}/dist/portfolio
        bucket_name: dmitri-website
        project: dmitri-website
        home_page_path: index.html
        error_page_path: index.html
